//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTemplate.PaymentService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/OnlineServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PaymentService.IPaymentService")]
    public interface IPaymentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/GetData", ReplyAction="http://tempuri.org/IPaymentService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/GetData", ReplyAction="http://tempuri.org/IPaymentService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IPaymentService/GetDataUsingDataContractResponse")]
        WebTemplate.PaymentService.CompositeType GetDataUsingDataContract(WebTemplate.PaymentService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IPaymentService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WebTemplate.PaymentService.CompositeType> GetDataUsingDataContractAsync(WebTemplate.PaymentService.CompositeType composite);
        
        // CODEGEN: Generating message contract since the wrapper name (Request) of message Request does not match the default value (GetBillsByBusinessID)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/GetBillsByBusinessID", ReplyAction="http://tempuri.org/IPaymentService/GetBillsByBusinessIDResponse")]
        WebTemplate.PaymentService.Response GetBillsByBusinessID(WebTemplate.PaymentService.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/GetBillsByBusinessID", ReplyAction="http://tempuri.org/IPaymentService/GetBillsByBusinessIDResponse")]
        System.Threading.Tasks.Task<WebTemplate.PaymentService.Response> GetBillsByBusinessIDAsync(WebTemplate.PaymentService.Request request);
        
        // CODEGEN: Generating message contract since the wrapper name (Request) of message Request does not match the default value (GetSelectedBillsTotal)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/GetSelectedBillsTotal", ReplyAction="http://tempuri.org/IPaymentService/GetSelectedBillsTotalResponse")]
        WebTemplate.PaymentService.Response GetSelectedBillsTotal(WebTemplate.PaymentService.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/GetSelectedBillsTotal", ReplyAction="http://tempuri.org/IPaymentService/GetSelectedBillsTotalResponse")]
        System.Threading.Tasks.Task<WebTemplate.PaymentService.Response> GetSelectedBillsTotalAsync(WebTemplate.PaymentService.Request request);
        
        // CODEGEN: Generating message contract since the operation PaySelectedBills is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/PaySelectedBills", ReplyAction="http://tempuri.org/IPaymentService/PaySelectedBillsResponse")]
        WebTemplate.PaymentService.PaySelectedBillsResponse PaySelectedBills(WebTemplate.PaymentService.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/PaySelectedBills", ReplyAction="http://tempuri.org/IPaymentService/PaySelectedBillsResponse")]
        System.Threading.Tasks.Task<WebTemplate.PaymentService.PaySelectedBillsResponse> PaySelectedBillsAsync(WebTemplate.PaymentService.Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Request", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Request_Value;
        
        public Request() {
        }
        
        public Request(string Key, string Request_Value) {
            this.Key = Key;
            this.Request_Value = Request_Value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Response_Value;
        
        public Response() {
        }
        
        public Response(string Response_Value) {
            this.Response_Value = Response_Value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaySelectedBillsResponse {
        
        public PaySelectedBillsResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPaymentServiceChannel : WebTemplate.PaymentService.IPaymentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentServiceClient : System.ServiceModel.ClientBase<WebTemplate.PaymentService.IPaymentService>, WebTemplate.PaymentService.IPaymentService {
        
        public PaymentServiceClient() {
        }
        
        public PaymentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public WebTemplate.PaymentService.CompositeType GetDataUsingDataContract(WebTemplate.PaymentService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WebTemplate.PaymentService.CompositeType> GetDataUsingDataContractAsync(WebTemplate.PaymentService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebTemplate.PaymentService.Response WebTemplate.PaymentService.IPaymentService.GetBillsByBusinessID(WebTemplate.PaymentService.Request request) {
            return base.Channel.GetBillsByBusinessID(request);
        }
        
        public string GetBillsByBusinessID(string Key, string Request_Value) {
            WebTemplate.PaymentService.Request inValue = new WebTemplate.PaymentService.Request();
            inValue.Key = Key;
            inValue.Request_Value = Request_Value;
            WebTemplate.PaymentService.Response retVal = ((WebTemplate.PaymentService.IPaymentService)(this)).GetBillsByBusinessID(inValue);
            return retVal.Response_Value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebTemplate.PaymentService.Response> WebTemplate.PaymentService.IPaymentService.GetBillsByBusinessIDAsync(WebTemplate.PaymentService.Request request) {
            return base.Channel.GetBillsByBusinessIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebTemplate.PaymentService.Response> GetBillsByBusinessIDAsync(string Key, string Request_Value) {
            WebTemplate.PaymentService.Request inValue = new WebTemplate.PaymentService.Request();
            inValue.Key = Key;
            inValue.Request_Value = Request_Value;
            return ((WebTemplate.PaymentService.IPaymentService)(this)).GetBillsByBusinessIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebTemplate.PaymentService.Response WebTemplate.PaymentService.IPaymentService.GetSelectedBillsTotal(WebTemplate.PaymentService.Request request) {
            return base.Channel.GetSelectedBillsTotal(request);
        }
        
        public string GetSelectedBillsTotal(string Key, string Request_Value) {
            WebTemplate.PaymentService.Request inValue = new WebTemplate.PaymentService.Request();
            inValue.Key = Key;
            inValue.Request_Value = Request_Value;
            WebTemplate.PaymentService.Response retVal = ((WebTemplate.PaymentService.IPaymentService)(this)).GetSelectedBillsTotal(inValue);
            return retVal.Response_Value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebTemplate.PaymentService.Response> WebTemplate.PaymentService.IPaymentService.GetSelectedBillsTotalAsync(WebTemplate.PaymentService.Request request) {
            return base.Channel.GetSelectedBillsTotalAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebTemplate.PaymentService.Response> GetSelectedBillsTotalAsync(string Key, string Request_Value) {
            WebTemplate.PaymentService.Request inValue = new WebTemplate.PaymentService.Request();
            inValue.Key = Key;
            inValue.Request_Value = Request_Value;
            return ((WebTemplate.PaymentService.IPaymentService)(this)).GetSelectedBillsTotalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebTemplate.PaymentService.PaySelectedBillsResponse WebTemplate.PaymentService.IPaymentService.PaySelectedBills(WebTemplate.PaymentService.Request request) {
            return base.Channel.PaySelectedBills(request);
        }
        
        public void PaySelectedBills(string Key, string Request_Value) {
            WebTemplate.PaymentService.Request inValue = new WebTemplate.PaymentService.Request();
            inValue.Key = Key;
            inValue.Request_Value = Request_Value;
            WebTemplate.PaymentService.PaySelectedBillsResponse retVal = ((WebTemplate.PaymentService.IPaymentService)(this)).PaySelectedBills(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebTemplate.PaymentService.PaySelectedBillsResponse> WebTemplate.PaymentService.IPaymentService.PaySelectedBillsAsync(WebTemplate.PaymentService.Request request) {
            return base.Channel.PaySelectedBillsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebTemplate.PaymentService.PaySelectedBillsResponse> PaySelectedBillsAsync(string Key, string Request_Value) {
            WebTemplate.PaymentService.Request inValue = new WebTemplate.PaymentService.Request();
            inValue.Key = Key;
            inValue.Request_Value = Request_Value;
            return ((WebTemplate.PaymentService.IPaymentService)(this)).PaySelectedBillsAsync(inValue);
        }
    }
}
