//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NavMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NavMenu()
        {
            this.NavMenu1 = new HashSet<NavMenu>();
            this.Pages = new HashSet<Page>();
        }
    
        public int ID { get; set; }
        public string NavTitle { get; set; }
        public Nullable<int> NavOrder { get; set; }
        public Nullable<int> NavPageID { get; set; }
        public Nullable<int> NavParentMenu { get; set; }
        public string NavIconClass { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NavMenu> NavMenu1 { get; set; }
        public virtual NavMenu NavMenu2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Page> Pages { get; set; }
    }
}
