//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Page()
        {
            this.PageAccesses = new HashSet<PageAccess>();
        }
    
        public int ID { get; set; }
        public string PageName { get; set; }
        public string URL { get; set; }
        public string Module { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string UserManualURL { get; set; }
        public Nullable<bool> accessibleByAll { get; set; }
        public Nullable<int> NavMenuId { get; set; }
        public Nullable<int> PageOrder { get; set; }
        public string Namespace { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Application { get; set; }
    
        public virtual NavMenu NavMenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PageAccess> PageAccesses { get; set; }
    }
}
