//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personnel()
        {
            this.Users = new HashSet<User>();
        }
    
        public long ID { get; set; }
        public string Employee_No { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> Date_Hired { get; set; }
        public Nullable<int> Employment_Status_ID { get; set; }
        public Nullable<System.DateTime> Resignation_Date { get; set; }
        public string Resignation_Remarks { get; set; }
        public Nullable<System.DateTime> Birth_Date { get; set; }
        public string Birth_Place { get; set; }
        public string Address { get; set; }
        public string Telephone_No { get; set; }
        public string Mobile_No { get; set; }
        public Nullable<int> Civil_Status_ID { get; set; }
        public Nullable<int> Religion_ID { get; set; }
        public string Other_Religion { get; set; }
        public Nullable<int> Personnel_Type_ID { get; set; }
        public Nullable<byte> Personnel_Location_ID { get; set; }
        public string Other_Location { get; set; }
        public Nullable<int> Position_ID { get; set; }
        public Nullable<int> Department_ID { get; set; }
        public Nullable<int> Employment_Type_ID { get; set; }
        public Nullable<byte> Tax_Type_ID { get; set; }
        public string SSS { get; set; }
        public string Philhealth { get; set; }
        public string PAGIBIG { get; set; }
        public string TIN { get; set; }
        public string Emergency_Contact_Person { get; set; }
        public string Emergency_Contact_Address { get; set; }
        public string Emergency_Contact_Number { get; set; }
        public string Email { get; set; }
        public string Referred_By { get; set; }
        public string Reference_Contact_No { get; set; }
        public Nullable<bool> Walk_In { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public string Image_Path { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        public virtual Department Department { get; set; }
    }
}
