//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Designations = new HashSet<Designation>();
            this.Designations1 = new HashSet<Designation>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> UserStatusID { get; set; }
        public string Prefix { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string Password { get; set; }
        public string EmailAddress { get; set; }
        public string MobileNumber { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public Nullable<int> CityID { get; set; }
        public string Zip { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> SignOnAttempts { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<System.DateTime> LastLogoutDate { get; set; }
        public Nullable<System.DateTime> LastPasswordChange { get; set; }
        public Nullable<bool> ForcePasswordChange { get; set; }
        public string LastSessionID { get; set; }
        public string LastInternalIPAddressUsed { get; set; }
        public string LastExternalIPAddressUsed { get; set; }
        public string LastMacAddressUsed { get; set; }
        public string LastWorkstationNameUsed { get; set; }
        public Nullable<bool> LoggedOn { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<int> LastModifiedby { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string PasswordSalt { get; set; }
        public Nullable<bool> isVerifiedEmailAddress { get; set; }
        public Nullable<bool> isVerifiedMobileNumber { get; set; }
        public Nullable<long> Personnel_ID { get; set; }
    
        public virtual Personnel Personnel { get; set; }
        public virtual UserStatu UserStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Designation> Designations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Designation> Designations1 { get; set; }
    }
}
