//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WebDBEntities : DbContext
    {
        public WebDBEntities()
            : base("name=WebDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Personnel> Personnels { get; set; }
        public virtual DbSet<Error> Errors { get; set; }
        public virtual DbSet<NavMenu> NavMenus { get; set; }
        public virtual DbSet<PageAccess> PageAccesses { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<Parameter> Parameters { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserStatu> UserStatus { get; set; }
        public virtual DbSet<VerificationCode> VerificationCodes { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
    
        public virtual int sp_SendSMSMessage(string varNumber, string varMessage)
        {
            var varNumberParameter = varNumber != null ?
                new ObjectParameter("varNumber", varNumber) :
                new ObjectParameter("varNumber", typeof(string));
    
            var varMessageParameter = varMessage != null ?
                new ObjectParameter("varMessage", varMessage) :
                new ObjectParameter("varMessage", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SendSMSMessage", varNumberParameter, varMessageParameter);
        }
    }
}
